name: Build ready-to-use ArchLinux image for AllWinner D1

on:
  push:
    tags:
      - 'r*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch repo
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recommend-shallow

      - name: Prepare environment
        run: |
          sudo apt update && sudo apt install -y \
            build-essential coreutils git bash \
            gawk cpio swig \
            parted \
            gzip zstd xz-utils \
            flex bison openssl libssl-dev \
            autoconf llvm \
            gcc-riscv64-linux-gnu \
            arch-install-scripts \
            qemu-user-static binfmt-support \
            libncurses-dev libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev

      - name: Build and compress system image
        run: |
          make -j $(nproc) \
            IMAGE="archlinux-d1-${{ github.event.commits[0].id }}.img" \
            SHELL="/bin/bash" \
            EXPKGS="networkmanager" \
            image \
          && xz -z "archlinux-d1-${{ github.event.commits[0].id }}.img"

      - name: Extract tag annotation
        id: tag-data
        uses: ericcornelissen/git-tag-annotation-action@v2

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.img.xz,output/*"
          body: ${{ steps.tag-data.outputs.git-tag-annotation }}

